### ISSUE TITLE
Export labels to R

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#101]
A user should be able to export a syntax file for reading their dataset using labels, just like they can currently with SPS files in SPSS.

**Comment by Edouard-Legoupil** [comment]
In order to provide an example of syntax comparison:

.sps value woudl be following for a 4 questions survey that would include diverse questions such as one free text, one date, one select, one integer question and one yes/no question encoded with integer:

```survey123.sps```
```
VARIABLE LABELS
    dG_AEnumerator "Assessor name"
    dG_ADate "Date of assessment"
    dG_AOrganisation_name "Organisation name"
    dG_Anumber "Number of person"
    dG_like "Did you like it?"

VALUE LABELS
    dG_AOrganisation_name
        'IRC' "IRC"          'other' "Other"        'unhcr' "UNHCR"
    dG_like
        '1' "yes"          '2' "No"      
```
in R the equivalent syntax file would be ```survey123_R_syntax.R```:

```
data <- read.table("survey123_R_data_file.csv", sep=",", quote = "'", na.strings=c("","\"\""), stringsAsFactors=FALSE)

data[, 1] <- as.character(data[, 1])
attributes(data)$variable.labels[1] <- "Assessor name"
names(data)[1] <- "dG_AEnumerator"

## Depending on the date format style
data[, 2] <- as.date()<- as.Date(as.character(data[, 2]), "%d-%m-%Y") 
attributes(data)$variable.labels[2] <- "Date of assessment"
names(data)[2] <- "dG_ADate"

attributes(data)$variable.labels[3] <- "Organisation name"
data[, 3] <- factor(data[, 3], levels=c( "IRC", "other",  "unhcr"),labels=c( "IRC","Other","UNHCR"))
names(data)[3] <- "dG_AOrganisation_name"

data[, 4] <- as.numeric(data[, 4])
attributes(data)$variable.labels[4] <- "Number of person"
names(data)[4] <- "dG_Anumber"

data[, 5] <- as.numeric(data[, 5])
attributes(data)$variable.labels[5] <- "Did you like it?"
data[, 5] <- factor(data[, 5], levels=c( "1", "2"),labels=c( "Yes","No"))
names(data)[5] <- "dG_like"

```

Both Integer and Numeric can be imported as numeric.
geopoint can be imported as character. It's not difficult to parse and extract the coordinates...
for instance, depending on the constraint on GPS recording accuracy, a certain number of digit after . will be recorded
```
data[,6] <- as.character(data[,6])
options(digits = 15)
data$lat <- as.numeric(substr(data[,6] , 1,13))
data$long <- as.numeric(substr(data[,6], 15,27))
```

**Comment by tinok** [comment]
Thanks! I propose we separate this issue into two parts: One to take care of labeling variables and options, and one for taking care of all the import steps from CSV. (The SPSS syntax file doesn't cover the import steps from CSV either at this point.)

@Edouard-Legoupil Are there any restrictions regarding the length of variable labels and option labels? Do non-ASCII characters need to be escaped?

**Comment by Edouard-Legoupil** [comment]
To my knowledge, there's no restrictions for label length. Note that the variable has two distinct attributes (name & label) and that there are restriction on name length. Names are limited to 10,000 bytes (and were to 256 bytes in versions of R before 2.13.0).

**Comment by Edouard-Legoupil** [comment]
FYI -- Ihave implemented those functions in a R package: https://github.com/Edouard-Legoupil/koboloadeR

**Comment by tinok** [comment]
Thanks so much @Edouard-Legoupil. We'll add a support page for this, pointing to your repo. Closing this issue now.
