### ISSUE TITLE
Anonymous/non-edit users can see 'add note to instance' fields

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#113]
A publicly shared dataset displays the 'add note to instance' fields but shouldn't (since anonymous users don't have permissions to add notes). 

![image](https://cloud.githubusercontent.com/assets/673511/12044769/508c6ec8-ae65-11e5-97fc-7260b9cd8ce0.png)

To test visit: https://kc.kobotoolbox.org/hammerdirt/forms/Montreux/instance#/402151

**Comment by jnm** [comment]
The notes feature has been removed from KoBoCAT.
