### ISSUE TITLE
Upgrade to Django 1.9

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kobocat#114]
kobocat uses Django 1.6, which is not supported anymore. In the worst case that could mean security problems. So kobocat should be upgraded to use Django 1.9 instead of 1.6.
Are there plans or maybe even ongoing work on updating kobocat to a supported version of Django?

**Comment by jnm** [comment]
Thank you for your report. At this time, we're working to upgrade to Django 1.8, [which is an LTS release with three-year support](https://www.djangoproject.com/weblog/2015/apr/01/release-18-final/).

As such, I'm closing this issue in favor of https://github.com/kobotoolbox/kobocat/issues/122.
