### ISSUE TITLE
Migrate db gives error becasue of django version 1.6, still we use south?

### ISSUE THREAD

**Issue by AnandMoorthy** [kobotoolbox/kobocat#123]
Hi i am trying to install kobocat, while migrating the it throws an error
File "/home/anand/Dev/venv/local/lib/python2.7/site-packages/registration/migrations/0001_initial.py", line 5, in <module>
    from django.db import models,migrations
ImportError: cannot import name migrations

Any solution?
I am using 
Python - 2.7.6
Django - 1.6

**Comment by esmail** [comment]
It seems like you might not have South installed. See http://stackoverflow.com/questions/25651716/from-django-db-import-models-migrations-importerror-cannot-import-name-migrati/.
