### ISSUE TITLE
XLS files with only one sheet should work even if it's not labelled "survey"

### ISSUE THREAD

**Issue by ksamuel** [kobotoolbox/kobocat#130]
And the error message should be changed for: 

"You have several sheets in this file, you need to name one 'survey' to let the tool know which one it should read the form information from".

Other options: display a list of sheet names, and let the user select the one it want to use if none is called "survey"

**Comment by jnm** [comment]
not a bad idea, but probably won't happen because the XLSForm `survey` convention is so strong. also, there are other sheets used to store form information (`choices`, `settings`)
