### ISSUE TITLE
Allow non ascii characters in xls import

### ISSUE THREAD

**Issue by ksamuel** [kobotoolbox/kobocat#134]
When trying to upload an xls to create a form containing accents, I get:

```
The name 'éêë' is an invalid xml tag. Names must begin with a letter, colon, or underscore, subsequent characters can include numbers, dashes, and periods.
```

Given that the service will be used in many locations in the world, we have to expect people to use non ASCII characters. If you need to use a non ASCII identifier in a context where non ascii chars are not allowed, you can slug them with with a tool like https://pypi.python.org/pypi/Unidecode

**Comment by jnm** [comment]
These restrictions come from Pyxform:
https://github.com/XLSForm/pyxform/blob/1493706622c329fd2913ae691a902bca054250d4/pyxform/utils.py#L28-L34
https://github.com/XLSForm/pyxform/blob/1493706622c329fd2913ae691a902bca054250d4/pyxform/xls2json.py#L584-L594

Labels, which should be what everyone sees when collecting and analyzing data, already support Unicode.
