### ISSUE TITLE
Add additional links to Enketo web forms

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#140]
A user in KC should be able to access all the different links available: 

Type of link | What it does
----|----
`Field submissions`* | Allows submitting data offline (and online)
`Web Single submission` | Works like web submissions but after filling form displays thank you message instead of refreshing form
`Web Multiple submissions` | Data can only be submitted when online; ideal for online surveys
`Embeddable` | Looks better than the regular form when embedding it in an `iframe`
`Preview-only*` | Displays the form online-only for testing purposes (can't submit data)

\* these are the only links currently available in the UI

**Comment by tinok** [comment]
@emilykferguson These need to go on your list for UX

**Comment by tinok** [comment]
For the software integration, [here](https://github.com/kobotoolbox/enketo-express/blob/master/doc/APIv2.md) is where the API / URLs are documented for Enketo Express.

**Comment by MartijnR** [comment]
For the embeddable option it might be useful to return a HTML snippet that people can (slightly amend) and then cut-and-paste into e.g. a Wordpress page of their website ([example](http://enketo.github.io/enketo-iframe-demo/)).

```<iframe src="https://the.enketo.url" style="display:block; border: 1px solid black; height: 500px; width: 400px;"></iframe>```
