### ISSUE TITLE
Improve downloading large number of media files

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#145]
Currently a user with more than a certain number of photos/videos/recordings can't download them (zip export fails). This would either provide them a link of individual media file links or find a different way to download the files.

**Comment by dorey** [comment]
Would a page with links (downloadable by a download manager, for example) satisfy this issue?

**Comment by tinok** [comment]
Let's do this for now to deal with this problem. This would mean giving the user an HTML view with just links to each media asset in their project. It could be another view from `formpack`, limited to any `image`, `audio`, or `video` question. We could add a link to the ZIP exports page: 

"If you have many media attachments in your project the export might fail. In this case [click here]() to get to a list of all your files, and use a download manager to download them all."

| media_question1 | media_question2 | media_question3 | 
|---|---|---|
[filename.ext]() | [filename.ext]() | [filename.ext]() |
[filename.ext]() | [filename.ext]() | [filename.ext]() |
[filename.ext]() | [filename.ext]() | [filename.ext]() |
