### ISSUE TITLE
Logging out from KC redirects to form list page

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#163]
To reproduce: 
1. Use an account that's already using beta
2. Sign in and go to KC 
3. Click on Sign out

Expected: User is logged out and redirected to sign in page
Instead: User is redirected to /forms page

**Comment by jnm** [comment]
:joy: Well, it logs me out now, but after doing so bids me farewell with
> Thank you for using Ona, please come again!

![image](https://user-images.githubusercontent.com/2085013/99867051-3af8e680-2b84-11eb-9ca7-4f1e35f8b75c.png)
