### ISSUE TITLE
SPSS zip fails with non-ascii character in response value

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#169]
If a form uses a non-ASCII character in the response 'name' column the SPSS download fails with a 500 error.  Not sure what the offending character is, but it's specific to at least one form. See http://sentry.kbtdev.org/kobo/kobocat/group/623/. To reproduce use [this file](https://github.com/kobotoolbox/kobocat/files/337319/kc-issue-169.xlsx).

**Comment by tinok** [comment]
Good news - found the cause for this bug. (Updated description and added file to reproduce issue above.)

**Comment by esmail** [comment]
Closing this as a `wontfix` as I believe non-ASCII characters are not supported as question and value *names* (as opposed to labels) in multiple parts of the system. Re-opening #296 instead.
