### ISSUE TITLE
Put dropdown options inside html tables

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#178]
The HTML tables should include dropdowns at the top to allow users to switch between for label selector and grouping on-off on top of table. When the user switches between the dropdown options the table should refresh.  

![image](https://cloud.githubusercontent.com/assets/673511/14833898/76d58084-0bcf-11e6-8ea5-7a8bad3f2ccc.png)

**Comment by sametmax** [comment]
About the refreshing, I can setup some JS to reload the page automatically (right now it's a button). I don't know if this is important.

**Comment by ksamuel** [comment]
About the refreshing, I can setup some JS to reload the page automatically (right now it's a button). I don't know if this is important.
