### ISSUE TITLE
Current Analyze Data button should link to Digest

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#180]
The Analyze Data button should link to the first page of the automatic report, using the first available label language as the default display.

**Comment by ksamuel** [comment]
I now have a view getting the first label by default. Can you give me a link to the analyze data button so I can edit it to make it point to this view ?

**Comment by tinok** [comment]
@ksamuel https://kc.kobotoolbox.org/username/forms/formID/tables

In the UI: 

![image](https://cloud.githubusercontent.com/assets/673511/14854847/5620fd92-0c5f-11e6-923a-f41113e4ca38.png)
