### ISSUE TITLE
Excel analyser exports failing

### ISSUE THREAD

**Issue by esmail** [kobotoolbox/kobocat#181]

**Comment by esmail** [comment]
Probably a regression from `formpack` integration (URL changes?).

**Comment by ksamuel** [comment]
Details ?

**Comment by tinok** [comment]
@ksamuel Excel Analyser exports combine an existing XLS spreadsheet containing advanced formulas with the XLS export created by KC (the old one, not the formpack one). It's being exported at https://serverURL/username/exports/xformID/analyser/

**Comment by tinok** [comment]
This is currently failing on PROD but not staging

**Comment by tinok** [comment]
Now also failing on staging
