### ISSUE TITLE
Disaggregation testing issues

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#207]
- [x] select_one questions: the question responses are shown as XML instead of labels: [image](https://cloud.githubusercontent.com/assets/673511/15166027/c1669c7c-16e8-11e6-854f-1f2c272b4802.png)
- [x] Number/Decimal questions: It's missing the split-by labels (column 1 is empty): [image](https://cloud.githubusercontent.com/assets/673511/15166024/b6b8a842-16e8-11e6-9424-d18b031faf4b.png)
- [x] 'None' should be excluded from tables as a category (unless there's a response with that name)
- [ ] Header figures are incorrect for text and select_multiple questions:
1. correct: 4,792 out of 4,792 respondents answered this question (0 were without data). - Question type: 'select_one'
2. incorrect: 10,876 out of 10,876 respondents answered this question (0 were without data). - Question type: 'select_multiple'
3. incorrect: 617 out of 617 respondents answered this question (0 were without data). - Question type: 'text'
- The second one should read **4,792** out of **4,792** respondents answered this question (0 were without data). - Question type: 'select_multiple
- The third one should read **617** out of 4,792 respondents answered this question (**4175** were without data). - Question type: 'text'

**Comment by ksamuel** [comment]
> 'None' should be excluded from tables as a category (unless there's a response with that name) 

I removed the display of None as a value (left headers) and splitter (top header), and only in disagregation but not the regular report. Is that alright ?

**Comment by jnm** [comment]
No more KoBoCAT UI :sweat_smile:
