### ISSUE TITLE
Exports and report include deleted instances

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#208]
When a submission/instance was deleted from kobocat it is still included in exports (xls, csv, html) and automatic reports. 

To reproduce: 

1. add test instance
2. delete it from kc
3. open html view, download xls or csv, or open auto report

Expected: Deleted instance is no longer included

Instead: It's still included

**Comment by ksamuel** [comment]
Apparently kobocat uses soft delete for any entries. Entries are not really deleted, they are marked with "_deleted_at" filtered. I fixed it by filtering it as well.

**Comment by ksamuel** [comment]
I can't reproduce the issue.
