### ISSUE TITLE
Repeat group questions are displayed empty in digest report

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#219]
Desired behavior: Repeat questions are displayed like all other questions.

Ideally they should be displayed in the same location as where they occurred in the original form. 

[Report link on staging](https://kc.kbtdev.org/uganda_14/reports/ariEXFiJVt8nSx7CXn9XZE/digest.html)

![image](https://cloud.githubusercontent.com/assets/673511/15344442/e88e2eb4-1c74-11e6-8456-5a7afc0b74ed.png)

**Comment by jnm** [comment]
No more KoBoCAT UI :sweat_smile:
