### ISSUE TITLE
Certain passwords do not work with Collect and KC

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#226]
When setting a password in Collect that includes `&` or `'` (and possibly other special characters) the authentication is refused by KC. 

Potential solution: Don't allow user passwords containing characters disallowed by Collect.

**Comment by jnm** [comment]
Fascinating. Is this still a problem?

**Comment by Kalyan-Lama** [comment]
I tried setting my password with special characters such as `72MZrZx<<;K(/$6L` or `$&';:~!@#%^*KL` and they both worked for me pretty well. 

#### Steps followed to reproduce:

* Changed the password as outlined above (with special characters).
* Then configured my `Collect android app` under the **General Settings>Server**:

#### URL (depending on the server)
`https://kc.humanitarianresponse.info/username`
or
`https://kc.kobotoolbox.org/username`

#### Username
username

#### Password
`72MZrZx<<;K(/$6L` or `$&';:~!@#%^*KL`

***

#### Additional Observation:

Initially, we would configure the `Collect android app` under the **General Settings>Server** as follows:

#### URL (depending on the server)
`https://kc.humanitarianresponse.info`
or
`https://kc.kobotoolbox.org`

#### Username
username

#### Password
`72MZrZx<<;K(/$6L` or `$&';:~!@#%^*KL`

But now it's throwing an error message (as shown in the image below) while trying to connect to the KoBoToolbox server:

![Image 1](https://user-images.githubusercontent.com/50188479/99899828-40fddd00-2cd4-11eb-8688-92555578b019.jpg)

**Comment by tinok** [comment]
@Kalyan-Lama This may just be the error we were looking for. To be sure, you shouldn't set the URL to include your username (because that way it doesn't require the username since you probably don't have 'require authentication' set in your user profile. 

@jnm This probably means is a bug with Collect, right?

**Comment by Kalyan-Lama** [comment]
@tinok, when checking `Require authentication to see forms and submit data` in the `KoBoToolbox Account Settings` i could not sync the `Collect android app` with the KoBoToolbox server as outlined here (which worked previously):

#### URL (depending on the server)
`https://kc.humanitarianresponse.info/username`
or
`https://kc.kobotoolbox.org/username`

#### Username
username

#### Password
`72MZrZx<<;K(/$6L` or `$&';:~!@#%^*KL` or `NewPassword`

**Comment by jnm** [comment]
I think this bug report only concerns scenario 6 described below. However, for ease of use, we could proceed with Kalyan's more extensive testing to make sure that all possible combinations work as expected—even if, as I believe the [spec describes](https://docs.getodk.org/openrosa-authentication/#typical-interaction), Collect does not send any credentials in scenarios 1-4.

Scenario | “Require authentication to see…” is checked | URL contains username | Password has `&` or `'` characters
-- | -- | -- | --
1 | No | No | No
2 | No | No | Yes
3 | No | Yes | No
4 | No | Yes | Yes
5 | Yes | No | No
6 | Yes | No | Yes
7 | Yes | Yes | No
8 | Yes | Yes | Yes

I'll try to reproduce the "Form list download failed" error with scenario 6 locally.

**Comment by jnm** [comment]
I'm not having any issues downloading the form list, individual blank forms, or making submissions with:

* "Require authentication to see forms and submit data": checked
* URL configured in Collect: `kc.kobotoolbox.org`
* Username: `jnm_demo`
* Password: `&'&'blahblah&'&'`
* ODK Collect version v1.28.4

Kalyan, perhaps what you were seeing was caused by a temporary server problem or network issue? Feel free to re-open this issue if you continue to see the "Form list download failed" error.
