### ISSUE TITLE
Implement /formList?formID=....

### ISSUE THREAD

**Issue by MartijnR** [kobotoolbox/kobocat#230]
For performance reasons, it may be good to implement another part of the [OpenRosa Form Discovery API spec](https://bitbucket.org/javarosa/javarosa/wiki/FormListAPI). If the /formList request includes a `formID` query parameter, only list that form. 

Afaik only ODK Aggregate and Enketo's very own Centro app has implemented this. See https://enketo-aggregate.appspot.com/xformsList vs https://enketo-aggregate.appspot.com/xformsList?formID=advanced_notes (Just ignore that these links are for /xformsList vs /formList - that's just a historic Aggregate thing that doesn't show the proper /formList if accessed from browser without special OpenRosa header). 

I think the loading performance of first launches and previews may improve quite a bit for **accounts with lots of forms** on the Enketo side. I imagine it may also improve /formList serving performance on the KC side. 

(also implemented in Enketo Express recently https://github.com/kobotoolbox/enketo-express/issues/502)

**Comment by jnm** [comment]
I think you were right!
