### ISSUE TITLE
Missing columns in exports in case of identical question IDs

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#239]
When a form contains the same question name more than once (but in different parent groups) the export will only contain one of the questions, excluding the others. [test form](https://kc.kbtdev.org/uganda_14/reports/akEPkyNcJajVBhU2ssW3pu/export/)

Data entered: 
![image](https://www.dropbox.com/s/kylehib67lrkhys/Screenshot%202016-06-22%2008.42.03.png?dl=1)

Data in table: 
![image](https://cloud.githubusercontent.com/assets/673511/16266926/461eb782-3855-11e6-8114-679f34ce73bf.png)

Data in Excel:
![image](https://cloud.githubusercontent.com/assets/673511/16266956/5e743cd0-3855-11e6-995d-8308267a0a65.png)

**Comment by KeynesYouDigIt** [comment]
Happy to take this on starting this weekend!! will assign it to my self once I am able to block out the time

shoot me an emial any questions!
vince.buscarello@gmail.com

**Comment by KeynesYouDigIt** [comment]
@tinok Starting progress (finally) -- should this be moved to in progress or would you rather see a PR first?

**Comment by KeynesYouDigIt** [comment]
Also, do we have like a slack or IRC channel?

**Comment by jnm** [comment]
Hello and thanks for looking into this! You may have noticed that the export code in this KoBoCAT repository uses a pretty old version (the `kobocat-requirement` branch) of https://github.com/kobotoolbox/formpack/. We'll soon be using the latest version of `formpack` directly with [KPI](https://github.com/kobotoolbox/kpi/) (the form builder and main user-facing app) per https://github.com/kobotoolbox/kpi/pull/1461. This will replace the [current approach](https://github.com/kobotoolbox/kpi/blob/b350cb6e7fb1f18bece64f203e31b162e2f56181/kpi/deployment_backends/kobocat_backend.py#L366) where KPI calls out to KoBoCAT for XLS and CSV exports.

If you've already started fixing this on top of the `kobocat-requirement` branch of `formpack`, I'd be happy to help merge your work into the latest `master`. If you have a clone of one of the `kobotoolbox` repos but don't want to open a PR yet, please feel free to link to your work here.

**Comment by KeynesYouDigIt** [comment]
Would it be worth making a slack channel or do we already have too many communication methods?

**Comment by KeynesYouDigIt** [comment]
also, pip sync in KPI is giving me the following 
`$ pip-sync 
Cannot uninstall requirement adium-theme-ubuntu, not installed
`

not sure how to get deps going there

**Comment by tinok** [comment]
@KeynesYouDigIt There is a working PR that will be deployed soon that is fixing this issue. We're working through the last kinks and appreciate any testing. See https://github.com/kobotoolbox/kpi/pull/1461

**Comment by KeynesYouDigIt** [comment]
Thanks, ill take a look. Is there a good place to get a few tips on the dev environment? Ive almost got it up but would love to follow protocol @tinok
