### ISSUE TITLE
Missing data in versioned form

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#251]
From user support ticket

**Comment by jnm** [comment]
1. Create a form in KPI with a question called "first question";
1. Deploy the form; enter some data;
1. Edit the form in KPI, deleting "first question" and adding "second question";
1. Redeploy the form; enter more data;
1. Export the form as XLS from KC;
1. Observe the absence of "first question"

**Comment by tinok** [comment]
Since this can only be available/fixed through Formpack downloads, we should add a note to users that versioned forms will _not_ included questions removed from a previous form version.

**Comment by jnm** [comment]
Formpack problem now tracked at https://github.com/kobotoolbox/formpack/issues/99.
This issue will be closed once a warning is added to KC export screens.

**Comment by esmail** [comment]
Reconfirming this is still an issue.
