### ISSUE TITLE
Change `superuser_stats` to report only counts

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobocat#284]
The current [`superuser_stats` view](https://github.com/kobotoolbox/kobocat/blob/132efa3c63901d21e10e072464aea222fd8511fa/onadata/apps/logger/views.py#L766) returns too much data (one row per submission in the instances file). Change the report to include only monthly counts of instances, xforms, and users.

**Comment by emilykferguson** [comment]
count of instances (submissions) per month
count of forms per month
count of NEW users per month
