### ISSUE TITLE
CORS - Help

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobocat#321]
Hi team,

I wanted to show some of data from my installed kobo-docker, i'm trying to access it via jquery ajax but it show error of CORS.

>  XMLHttpRequest cannot load http://45.76.84.232:8001/api/v1/user. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

`$.ajax({
    method: "GET",
    url: 'http://myip/api/v1/user',
    dataType: 'json',
    xhrFields: {
        withCredentials: false
    },
    headers: {
        'Authorization': 'Token TOKEN_KEY'
    },
});`

Please help

**Comment by jnm** [comment]
Hello,

We don't use these CORS settings in our production servers, but perhaps they'll work for you:
https://github.com/kobotoolbox/kobocat/blob/7d6d40e2eab6707cfae477d8b824268e3dfd171e/onadata/settings/common.py#L287

Failing that, you might consult the CORS documentation for Django REST Framework. That's the library that KoBoCAT uses to expose endpoints like `/api/v1/user`. See http://www.django-rest-framework.org/topics/ajax-csrf-cors/#cors:
> The best way to deal with CORS in REST framework is to add the required response headers in middleware. This ensures that CORS is supported transparently, without having to change any behavior in your views.
>
> Otto Yiu maintains the django-cors-headers package, which is known to work correctly with REST framework APIs.

If you need further assistance, please send a message to support@kobotoolbox.org. Thanks!
