### ISSUE TITLE
Limit number of "prefetched" exports by each celery process

### ISSUE THREAD

**Issue by dorey** [kobotoolbox/kobocat#329]
`CELERYD_PREFETCH_MULTIPLIER` defaults to 4.

Look into reducing this number so that jobs don't hang behind stalled exports.

**Comment by jnm** [comment]
I find the Celery terminology a bit confusing: we only have one "worker" even if that worker has multiple subprocesses. There are two levels of message passing: one from the queue to the worker's parent process, and another from the worker's parent process to the worker's child subprocess.

`CELERYD_PREFETCH_MULTIPLIER` I believe affects the first level of message passing, which shouldn't have an impact on our situation. However, we should be able to invoke the worker with `-Ofair`, which directs the parent process to check that a child subprocess is actually idle before sending it more tasks.

Technical detail from Ask Solem:

> WIth -Ofair we only write to child processes that are not already processing a task,
so no, a child process running a task is not considered available for work.
> ...
> The prefork pool is implemented like a super-fast local broker, but where the consumers are the child processes executing tasks.  Like in AMQP the child processes do not “fetch” messages from the worker, they use pipe/socket communication with the parent process and will read from that pipe/socket whenever they want a new task to work on.  Here -Ofair attempts to solve the same problem as the AMQP prefetch limits do, but doesn’t have anything to do with AMQP.

https://groups.google.com/forum/#!topic/celery-users/8kTlKtOqxLg
