### ISSUE TITLE
Attachment Not found

### ISSUE THREAD

**Issue by awemulya** [kobotoolbox/kobocat#331]
kobocat_url/attachment/medium?media_file=wvin/attachments/1487227091101.jpg

`Attachment not found`

When XForm have many(4+) image field questions. This issue repeats.

e.g. in my submission there are 20 image uploads only 4 are visible(exists in media), rest doesnot exists in media directory.

I have this problem for 50+ surveys.

**Comment by colinjstief** [comment]
Same issue here. Did you ever find a resolution?

**Comment by kryptt** [comment]
I am getting empty attachments (0 bytes) in the list
