### ISSUE TITLE
ODK Briefcase Bug

### ISSUE THREAD

**Issue by iahmedani** [kobotoolbox/kobocat#359]
Dear Team,

I wanted to download my data using kobo briefcase but it gives me following error. please advise. 

> 
Fetching form definition
resolving against briefcase form definitions
Error parsing form definition: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: The data model does not have an id or xmlns attribute.  Add an id="your.domain.org:formId" attribute to the top-level instance data element of your form.

**Comment by aurdipas** [comment]
any update?

**Comment by smutnyleszek** [comment]
Isn't this a duplicate of #359?

**Comment by aurdipas** [comment]
Do you mean of #339? it looks nobody is working on these issues. No more compatibility between Kobo and Briefcase?

**Comment by smutnyleszek** [comment]
Yes, thanks :) I just think both issues are about the same, so they should be merged and discussion should take place in one of them.

**Comment by tinok** [comment]
Duplicate of #359, closing this issue.
