### ISSUE TITLE
shared forms not in formList

### ISSUE THREAD

**Issue by geomapdev** [kobotoolbox/kobocat#370]
When a form has been shared with another user, that form does still not show up in the user's formList:
https://[kobocat_url]/[username]/formList

Since the shared form is not showing up there, it's also not usable from KoboCollect.  Only the forms owned by the user can be downloaded and filled out using the mobile app.

**Comment by jnm** [comment]
Have you tried `https://[kobocat_url]/formList`? Including `[username]` by design restricts the list to only forms owned by the identified user.

**Comment by geomapdev** [comment]
I just tried that, and same result.  The shared forms don't show up after authenticating with that page, only the forms owned by the user you authenticate as.

The main issue is that these instructions in the UI (kpi) don't work as described for a shared form:

1. Install KoboCollect on your Android device.
2. Click on  to open settings.
3. Enter the server URL https://kobocat.swcacloud.com/[username] and your username and password
4. Open "Get Blank Form" and select this project.
5. Open "Enter Data."

Step 4 is not possible because the shared form does not display in KoboCollect or ODK Collect.

**Comment by jnm** [comment]
Permissions are confusing right now: there's the KPI sharing UI, which
governs form definitions only, and the KC sharing settings, which control
submissions and data access. The latter are also presented in KPI within an
iframe in the form settings (not sharing) section.

This is getting cleaned up per
https://github.com/kobotoolbox/kpi/issues/1299. It's recently closed, but
the changes haven't been deployed anywhere yet.

Please check that you've assigned the "Can submit to" permission through
the settings iframe or through KC directly.

**Comment by geomapdev** [comment]
Ok, after setting the permission in the settings iframe, the user it is shared with can see it, but only when their username is not added to the URL (https://[kobocat_url]/formList instead of https://[kobocat_url]/[username]/formList)

So this may also require a change here to remove username from the URL to enter into Collect:
https://github.com/kobotoolbox/kpi/blob/5df858ba110c02c150780d72afcb7f8809723f2f/jsapp/js/components/formLanding.es6#L219

Should I submit an issue with KPI for that change?  Thanks.

**Comment by tinok** [comment]
@geomapdev That is accurate - the username (and the trailing slash) needs to be removed in order to access forms that have been shared with the user. Fixing this now in a PR.

**Comment by geomapdev** [comment]
Great, much appreciated!

**Comment by jnm** [comment]
@geomapdev, thanks for the report!
