### ISSUE TITLE
Upgrade DRF to a more recent version

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kobocat#397]
The version of DRF used by _kobocat_ is quite old and should be updated. I will create a PR that installs a more recent version of DRF and makes the necessary changes to work with the current release version.

**Comment by jeverling** [comment]
I tried to upgrade to the latest version, DRF 3.7.3. However, this is not possible at the moment, due to the oldest Django version supported by DRF 3.7.3 being Django 1.10.
Upgrading Django will likely be a much more involved process, so for the time being DRF 3.6.4 is the latest version we can use without having to upgrade Django.

**Comment by jnm** [comment]
Sorry we're so slow, but this will happen with #602!
