### ISSUE TITLE
Review ca. 2013 GitHub wiki and consider removal

### ISSUE THREAD

**Issue by paulauvirage** [kobotoolbox/kobocat#412]
Hi I am trying to follow advice here https://github.com/kobotoolbox/kobocat/wiki/How-to-add-media-files-to-forms on adding audio to files, but the links to the fully worked example spreadsheet and form on formhub seem to be broken. Is there anywhere else to access this information?

**Comment by jnm** [comment]
I'm embarrassed to admit that I did not know about this wiki. Please try the procedure at http://help.kobotoolbox.org/creating-forms/advanced/adding-media-to-your-form and contact help@kobotoolbox.org if you have any difficulty.

**Comment by jnm** [comment]
@emilykferguson, @tinok, I don't see any topics listed at https://github.com/kobotoolbox/kobocat/wiki that we don't cover elsewhere. Any reason I should not remove this GitHub wiki? I could put up a single page directing folks to help.kobotoolbox.org.

**Comment by tinok** [comment]
Yes please remove the wiki @jnm

**Comment by jnm** [comment]
Done
