### ISSUE TITLE
dot characters hashing is broken

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kobocat#416]
@jnm says:

> something between https://github.com/kobotoolbox/kobocat/releases/tag/2.018.05 and > https://github.com/kobotoolbox/kobocat/releases/tag/2.017.46 broke hashing of chars like `.` 
> that  are invalid keys for Mongo.

**Comment by jnm** [comment]
It was really `__` in field names that was causing the problem, since those were being interpreted as separators for nested properties. Fixed by https://github.com/kobotoolbox/kobocat/pull/417
