### ISSUE TITLE
Decoding names with dots from Mongo doesn't work

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kobocat#420]

**Comment by jnm** [comment]
@noliveleger, could you add some more detail? I think this affects the data API only, but if it's a problem in other places, please note that. Also it'd be good to set `bug` as a label.

**Comment by noliveleger** [comment]
@jnm. Agree. I just wanted a issue number to create the branch. I'm gonna update it soon.

**Comment by noliveleger** [comment]
When data is submitted to Mongo, the data is passed though mechanism that encodes invalid characters for Mongo. (ie. `.` and `$`) 
For example: `{ "my.attribute": True }` becomes `{ "myLg==attribute": True }`
When we retrieve this data from Mongo, serializers return data with encoded attributes although it should return decoded ones.

**Comment by jnm** [comment]
Fixed by #421.
