### ISSUE TITLE
New project from scratch keeps loading.

### ISSUE THREAD

**Issue by awemulya** [kobotoolbox/kobocat#431]
![screenshot from 2018-03-21 08-46-22](https://user-images.githubusercontent.com/5351212/37693172-0e4cba02-2ce6-11e8-8e94-2db63512c18c.png)

**Comment by jnm** [comment]
Could you please check the console and network facilities of your browser's developer tools for any errors? Then, please post what you find as a new issue in https://github.com/kobotoolbox/kpi/. This repository is only for "Projects (legacy)" and communication with the KoBoCollect and Enketo data collection clients.
