### ISSUE TITLE
Not all attachments are saved

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobocat#432]
See also:
* https://github.com/kobotoolbox/enketo-express/issues/776
* https://github.com/kobotoolbox/kpi/issues/1679
* https://www.flowdock.com/app/kobotoolbox/support/threads/3HHwfQ6VIlrSH2DWGKFuir-qWch
* (maybe related) https://github.com/kobotoolbox/kobocat/issues/124

KC returns success to the client but not all attachments are stored. More details to follow.

**Comment by colinjstief** [comment]
I can confirm this as well. I successfully receive 3-4 photos, but any more are not retrievable via Kobo client or API. Replicated on iPhone and desktop form.

**Comment by jnm** [comment]
For reference, here's an exchange between ODK Aggregate and KoBoCollect that was captured with a packet sniffer. It matches the [OpenRosa specification](https://docs.opendatakit.org/openrosa-form-submission/#extended-transmission-considerations):
> If a full POST of the form's XML submission and its additional parts (for example, captured image, audio or video clips) would exceed the size specified in the X-OpenRosa-Accept-Content-Length header (the maxSize), it is recommended that the client split the POST into multiple individual POST requests, each containing the form's XML submission and one or more additional parts such that each partial POST request is no greater than maxSize...

### Client Request 1
```
HEAD /submission?deviceID=imei%3A00000000000000 HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; Moto G (5) Plus Build/NPNS25.137-93-8) org.koboc.collect.android/v1.14.0a
X-OpenRosa-Version: 1.0
Date: Tue, 17 Apr 2018 12:20:29 GMT+00:00
Host: scrappy:10080
Connection: Keep-Alive
Accept-Encoding: gzip,deflate
```

### ⬆ _Server Response 1_
```
HTTP/1.1 204
X-OpenRosa-Version: 1.0
Date: Tue, 17 Apr 2018 00:20:30 GMT
X-OpenRosa-Accept-Content-Length: 10485760
Location: http://scrappy:10080/submission
```

### Client Request 2
```
POST /submission?deviceID=imei%3A00000000000000 HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; Moto G (5) Plus Build/NPNS25.137-93-8) org.koboc.collect.android/v1.14.0a
X-OpenRosa-Version: 1.0
Date: Tue, 17 Apr 2018 12:20:30 GMT+00:00
Content-Length: 9469179
Content-Type: multipart/form-data; boundary=A-JYpf-ZPbtl0ItnGY5m28v_JNAQO2dve_8vI63
Host: scrappy:10080
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

--A-JYpf-ZPbtl0ItnGY5m28v_JNAQO2dve_8vI63
Content-Disposition: form-data; name="xml_submission_file"; filename="several pic_2_2018-04-16_20-19-34.xml"
Content-Type: text/xml; charset=ISO-8859-1
Content-Transfer-Encoding: binary

<?xml version='1.0' ?><data id="snapshot_xml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:h="http://www.w3.org/1999/xhtml"><start>2018-04-16T20:19:34.499-04</start><end>2018-04-16T20:20:21.951-04</end><not_a_pic>6699</not_a_pic><pic_group><a_pic>1523924391480.jpg</a_pic></pic_group><pic_group><a_pic>1523924400575.jpg</a_pic></pic_group><pic_group><a_pic>1523924410434.jpg</a_pic></pic_group><pic_group><a_pic>1523924417719.jpg</a_pic></pic_group><meta><instanceID>uuid:51fff840-fe82-4fe3-9249-d8f6b14251e5</instanceID></meta></data>
--A-JYpf-ZPbtl0ItnGY5m28v_JNAQO2dve_8vI63
Content-Disposition: form-data; name="1523924391480.jpg"; filename="1523924391480.jpg"
Content-Type: image/jpeg
Content-Transfer-Encoding: binary
<snip>
--A-JYpf-ZPbtl0ItnGY5m28v_JNAQO2dve_8vI63
Content-Disposition: form-data; name="1523924400575.jpg"; filename="1523924400575.jpg"
Content-Type: image/jpeg
Content-Transfer-Encoding: binary
<snip>
--A-JYpf-ZPbtl0ItnGY5m28v_JNAQO2dve_8vI63
Content-Disposition: form-data; name="*isIncomplete*"
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

yes
--A-JYpf-ZPbtl0ItnGY5m28v_JNAQO2dve_8vI63--
```

### ⬆ _Server Response 2_
```
HTTP/1.1 201
Location: http://scrappy:10080/submission
X-OpenRosa-Version: 1.0
Date: Tue, 17 Apr 2018 00:20:32 GMT
X-OpenRosa-Accept-Content-Length: 10485760
Content-Type: text/xml;charset=UTF-8
Content-Length: 336

<OpenRosaResponse xmlns="http://openrosa.org/http/response"><message>partial submission upload was successful!</message><submissionMetadata xmlns="http://www.opendatakit.org/xforms" id="snapshot_xml" instanceID="uuid:51fff840-fe82-4fe3-9249-d8f6b14251e5" submissionDate="2018-04-17T00:20:31.888Z" isComplete="false"/></OpenRosaResponse>
```

### Client Request 3
```
POST /submission?deviceID=imei%3A00000000000000 HTTP/1.1
User-Agent: Dalvik/2.1.0 (Linux; U; Android 7.0; Moto G (5) Plus Build/NPNS25.137-93-8) org.koboc.collect.android/v1.14.0a
X-OpenRosa-Version: 1.0
Date: Tue, 17 Apr 2018 12:20:32 GMT+00:00
Content-Length: 7016691
Content-Type: multipart/form-data; boundary=hs5wdY7HOGgr9_TcU8w6-q5RaU3Tn_Mz5wmGW
Host: scrappy:10080
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

--hs5wdY7HOGgr9_TcU8w6-q5RaU3Tn_Mz5wmGW
Content-Disposition: form-data; name="xml_submission_file"; filename="several pic_2_2018-04-16_20-19-34.xml"
Content-Type: text/xml; charset=ISO-8859-1
Content-Transfer-Encoding: binary

<?xml version='1.0' ?><data id="snapshot_xml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:h="http://www.w3.org/1999/xhtml"><start>2018-04-16T20:19:34.499-04</start><end>2018-04-16T20:20:21.951-04</end><not_a_pic>6699</not_a_pic><pic_group><a_pic>1523924391480.jpg</a_pic></pic_group><pic_group><a_pic>1523924400575.jpg</a_pic></pic_group><pic_group><a_pic>1523924410434.jpg</a_pic></pic_group><pic_group><a_pic>1523924417719.jpg</a_pic></pic_group><meta><instanceID>uuid:51fff840-fe82-4fe3-9249-d8f6b14251e5</instanceID></meta></data>
--hs5wdY7HOGgr9_TcU8w6-q5RaU3Tn_Mz5wmGW
Content-Disposition: form-data; name="1523924410434.jpg"; filename="1523924410434.jpg"
Content-Type: image/jpeg
Content-Transfer-Encoding: binary
<snip>
--hs5wdY7HOGgr9_TcU8w6-q5RaU3Tn_Mz5wmGW
Content-Disposition: form-data; name="1523924417719.jpg"; filename="1523924417719.jpg"
Content-Type: image/jpeg
Content-Transfer-Encoding: binary
<snip>
--hs5wdY7HOGgr9_TcU8w6-q5RaU3Tn_Mz5wmGW--
```

### ⬆ _Server Response 3_
```
HTTP/1.1 201
Location: http://scrappy:10080/submission
X-OpenRosa-Version: 1.0
Date: Tue, 17 Apr 2018 00:20:34 GMT
X-OpenRosa-Accept-Content-Length: 10485760
Content-Type: text/xml;charset=UTF-8
Content-Length: 380

<OpenRosaResponse xmlns="http://openrosa.org/http/response"><message>full submission upload was successful!</message><submissionMetadata xmlns="http://www.opendatakit.org/xforms" id="snapshot_xml" instanceID="uuid:51fff840-fe82-4fe3-9249-d8f6b14251e5" submissionDate="2018-04-17T00:20:31.888Z" isComplete="true" markedAsCompleteDate="2018-04-17T00:20:33.727Z"/></OpenRosaResponse>
```

## ODK Aggregate behavior

* Submission `POST` handler: https://github.com/opendatakit/aggregate/blob/59083e7c25d2c54ed77edcb468bbaa7d0470be27/src/main/java/org/opendatakit/aggregate/servlet/SubmissionServlet.java#L208-L298
* [According to Mitchell Sundt](https://forum.opendatakit.org/t/sending-batch-inform-in-submission-header/5513/4), "ODK Aggregate does not pay attention to [`isIncomplete`]. It evaluates completeness by inspecting the content of the submission." Indeed, [it looks like](https://github.com/opendatakit/aggregate/blob/2786f4a52165a93a14768c4ba7a4e97ea6bcf7c6/src/main/java/org/opendatakit/aggregate/parser/SubmissionParser.java#L573-L634) Aggregate:
  * considers the form definition when processing submissions to determine which fields should have attachments;
  * looks through the multi-part form data for attachments specifically referenced in the submission XML;
  * ascertains a submission's completeness by making sure attachments were received for all fields that should have them.
* KoBoCAT, on the other hand, doesn't concern itself with the form definition and stores all attachments without checking whether they are actually referenced by the submission XML. **The problem here**, and the reason why attachments were lost, is that the entire contents of a submission were [considered to be duplicate](https://github.com/kobotoolbox/kobocat/blob/7448f30b29e9e72ccc2071cadddce15de8abb035/onadata/libs/utils/logger_tools.py#L249-L253) if the XML alone (`xml_submission_file`) was duplicate, and a [202 response](https://github.com/kobotoolbox/kobocat/blob/7448f30b29e9e72ccc2071cadddce15de8abb035/onadata/libs/utils/logger_tools.py#L306-L310) was returned without storing any new attachments that may have accompanied the duplicate XML. It seems that [other code](https://github.com/kobotoolbox/kobocat/blob/7448f30b29e9e72ccc2071cadddce15de8abb035/onadata/libs/utils/logger_tools.py#L261-L265) ([see also](https://github.com/kobotoolbox/kobocat/commit/5771a4775e4ca6f70af7038baa1874f7fd3fdbdd)) whose purpose was to "`ensure we have saved the extra attachments`" could never have been reached.

**Comment by colinjstief** [comment]
We seem to be experiencing the same issue of some photos not making it. This is a screenshot from kf.kobotoolbox.org dashboard. In this instance, the collector added photos from her phone.

<img width="956" alt="screenshot 2018-05-29 09 38 51" src="https://user-images.githubusercontent.com/1825668/40662432-52235cf8-6324-11e8-8f7d-1780901975a8.png">

**Comment by jnm** [comment]
@colinjstief, could you report this to our support team by using the bubble at the bottom, right-hand corner of the screen? We'd need to investigate your particular form and submissions to troubleshoot. Alternatively, if you have a list of steps that reproduces this problem, please reopen this issue or create a new one. I don't always notice comments posted to closed issues. Thank you.

**Comment by colinjstief** [comment]
@jnm Sure thing, I will report it to the support team. I was hoping to post steps to reproduce the problem, but it has been tricky to track down exactly what causes it because it happens intermittently. When it has happened, we think (a) there was some period of lost connectivity during field collection, or (b) the collector saved a draft and came back to the form later to attach the photos.

**Comment by kryptt** [comment]
We have just noticed we have some 0 byte attachments ourselves.
