### ISSUE TITLE
Multiple submissions of same form

### ISSUE THREAD

**Issue by colinjstief** [kobotoolbox/kobocat#441]
Recently, we are experiencing multiple submission records of the same form. Typically, four (4) come in to the system and appear identical, even down to attributes "_xform_id_string" and  "meta/instanceID". Not sure if this is related to #432 , which I know was recently closed. We are using web forms from mobile devices and sending to https://kf.kobotoolbox.org

**Comment by jnm** [comment]
This is now tracked at #470
