### ISSUE TITLE
read-only enketo view for records

### ISSUE THREAD

**Issue by willywutang** [kobotoolbox/kobocat#460]
It would be ideal to provide a read-only view that has Enketo support. 

Currently we see Enketo through Kobotoolbox when records are being edited, but it would also be ideal to use Enketo's view for read-only browsing of records.

The Enketo view is easier to read than the current tabular view in KoboToolbox, and provide the exact same interface used by desktop-based submitters of the data.

Enketo already provides API support for this:

     https://apidocs.enketo.org/v2#/post-instance-view

**Comment by awemulya** [comment]
https://enke.to/api/v2/instance/view
I have tried to implement this Readonly view of record. But Enketo is showing some error.

https://github.com/enketo/enketo-express/issues/75
Hope enketo will responds soon.

**Comment by awemulya** [comment]
https://github.com/kobotoolbox/kobocat/pull/513

I have created pull reequest Its working.

**Comment by jnm** [comment]
We're not going to add any new UI to KoBoCAT, but we are working on adding this feature to KPI: https://github.com/kobotoolbox/kpi/issues/2607
