### ISSUE TITLE
Replacing form_logo.png raises a 500 error

### ISSUE THREAD

**Issue by jeverling** [kobotoolbox/kobocat#461]
When a `form_logo.png` is used for branding of a form, and a different file is uploaded with the same name, *kobocat* raises a 500 error:

```
IntegrityError at /kobocat/kimetrica/forms/azdsLSMZ4VP36FAaot5Xo2/edit
duplicate key value violates unique constraint "main_metadata_xform_id_650ce6c23f5e7049_uniq"
DETAIL:  Key (xform_id, data_type, data_value)=(12, media, form_logo.png) already exists.
```

When the file is deleted before the changed version is uploaded, it works fine.

I think the file should either be replaced, or an error message should be displayed instead of raising a 500.

**Comment by jnm** [comment]
I think this is true of any form attachment file. We're going to have KPI handle these files in the future, and it will handle name collisions properly. https://github.com/kobotoolbox/kpi/issues/2673
