### ISSUE TITLE
The API is severly broken and misdocumented

### ISSUE THREAD

**Issue by Humblehound** [kobotoolbox/kobocat#494]
The entire Kobocat API has several major issues:

- The filtering API supports MongoDB query language, which I only found out by trial and error. Filtering such as  `api/v1/data/2?query={"$or": [{"fieldA":  "valueA"}, {"fieldB":"valueB"]]}` works but this is nowhere to be found in the documentation. 
- The `api/v1/charts` endpoint always returns HTML data. In order to get results that are in the documentation, you have to specify fields and response type like this `api/v1/charts/31?format=json&fields=all`
- `charts` endpoint does not include text question type data. Part of the response:
```"Text_question": {
        "field_type": "text",
        "data_type": "categorized",
        "field_xpath": "Text_question",
        "data": [
            {
                "count": 1,
                "Text_question": []
            },
            {
                "count": 1,
                "Text_question": []
            },
            {
                "count": 3,
                "Text_question": []
            }
        ],
        "field_label": "Text question",
        "field_name": "Text_question"
    }, 
```
As you can see the values of the responses are missing. Other question types, such as number or choice, are displayed correctly. 

- if no data is found on `stats` endpoint , an error is returned:
`400: { "detail": "zero-size array to reduction operation maximum which has no identity"}`

**Comment by jnm** [comment]
The MongoDB query support is described in the online API documentation:
![image](https://user-images.githubusercontent.com/2085013/56280700-c07b0180-60d8-11e9-8329-b1fd5906bcdb.png)
This was added roughly 5 years ago: https://github.com/kobotoolbox/kobocat/blame/b5b507d7e543e69a1d3a3b190407fecf42a1efa7/onadata/apps/api/viewsets/data_viewset.py#L185.

Thanks for your report about `charts` and `stats`. We will remove these as soon as possible; see https://github.com/kobotoolbox/kobocat/issues/549.

**Comment by Humblehound** [comment]
Thanks, I recall I couldn't find the description of the query language anywhere, perhaps it was added since. Glad you're working on the other issues.
