### ISSUE TITLE
Extend S3 media expiration to 7 days

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#499]
Users with a slow connection can't download the zipped media attachment file from S3 because it expires after 2h. 

We should extend it to 7 days.

**Comment by noliveleger** [comment]
@tinok. I'm closing this issue in favor of https://github.com/kobotoolbox/kobocat/pull/502. 
S3 links won't be exposed anymore and users will only see `kobocat` endpoint (even in their browser download manager)
Users won't have to worry about S3 expiration anymore.
