### ISSUE TITLE
Images collected after 11/21/18 cannot be found through hyperlink

### ISSUE THREAD

**Issue by mdestaubin** [kobotoolbox/kobocat#500]
Following the instructions on the support page to create hyperlinks to view collected images, an error message says the item cannot be found. This only occurs on images collected on the OCHA server and collected after the date of 11/21/18. It is believed to be connected to this PR - https://github.com/kobotoolbox/kobocat/pull/496

**Comment by mdestaubin** [comment]
Flowdock thread can be found here - https://www.flowdock.com/app/kobotoolbox/support/threads/Y3qL4S2aFW9CGHux6ZPCpT_kMDr?filter=search&query=favicon

**Comment by noliveleger** [comment]
For references:
http://support.kobotoolbox.org/managing-your-project-s-data/data-exports/downloading-photos-and-other-media
