### ISSUE TITLE
Upgrade to python 3.* and Django 2.*

### ISSUE THREAD

**Issue by awemulya** [kobotoolbox/kobocat#529]
The End Of Life date (EOL, sunset date) for Python 2.7 is near ( to 2020)
Django 1.8.* (LTS) support was  April 1, 2018

Is there any plan to Upgrade code to python 3 and django 2 ?? (2.2 LTS Support Until at least April 2022)

**Comment by jnm** [comment]
Whoops, looks like we duplicated this issue with #602. Please track the progress there.
