### ISSUE TITLE
Gallery View/ Data View/Enketo Edit  Attachments not Found.

### ISSUE THREAD

**Issue by awemulya** [kobotoolbox/kobocat#530]
![screenshot from 2019-03-07 05-48-06](https://user-images.githubusercontent.com/5351212/53922547-f0c48e80-409c-11e9-9549-bbd16e6947a8.png)

Attachment not found on Gallery View and Data View and Enketo edit view, But shown in open from kpi.

The files exists in Media dir. but atttachment view not returning media.
![screenshot from 2019-03-07 05-51-36](https://user-images.githubusercontent.com/5351212/53922722-9ed03880-409d-11e9-9358-63929bc9b73f.png)
![screenshot from 2019-03-07 05-50-25](https://user-images.githubusercontent.com/5351212/53922728-a42d8300-409d-11e9-96c7-33b61c0198e8.png)

**Comment by ajarocki** [comment]
This issue might be related: https://github.com/kobotoolbox/kobo-docker/issues/193

Check what url enketo edit view is using, if kc.kobotoolbox.org is in the url then setting KOBOCAT_URL as described in the linked issue should help.

**Comment by awemulya** [comment]
Nope Not docker issue. I have setup from source code.
I think some issue with attachment url view.

**Comment by awemulya** [comment]
attachment_url in viewer/views  Doesnot throws exception if  image_url fails instread it shows Attachment coundnot found.
     media_url = image_url(attachment, size)
image_url fails ( due to Pillow IOError: decoder jpeg not available)

> sudo apt-get install libjpeg-dev
Fixed my problem.

**Comment by awemulya** [comment]
Attachment url showing correct error message ie exception message on UI would be better.
