### ISSUE TITLE
Media urls are not formatted correctly

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kobocat#588]
`media_file=` argument is duplicated in the query string.
e.g. `https://kc.kobotoolbox.org/media/original?media_file=media_file=...jpg`

https://www.flowdock.com/app/kobotoolbox/kobo/threads/GxK0_moEECOtOcdHmLNZSdiOktn

**Comment by jnm** [comment]
**Management command `rewrite_attachments_urls_in_mongo` must be (re)run** to fix existing submissions.
