### ISSUE TITLE
audit question not imported to form builder - error "row could not be displayed"

### ISSUE THREAD

**Issue by danbjoseph** [kobotoolbox/kobocat#593]
Trying to implement this: http://support.kobotoolbox.org/en/articles/2648050-audit-logging-meta-question-type

![Screen Shot 2020-01-14 at 9 41 58 PM](https://user-images.githubusercontent.com/4806884/72400269-b5f8a180-3716-11ea-878e-844e1eee2511.png)

After uploading the XLSForm, opened the survey in the form-builder and was shown this error:

![Screen Shot 2020-01-14 at 9 38 31 PM](https://user-images.githubusercontent.com/4806884/72400196-834ea900-3716-11ea-9c0a-f4177fb00550.png)

**Comment by jnm** [comment]
This should be working now per https://github.com/kobotoolbox/kpi/issues/2187. If not, please re-open the issue on the KPI repository (that's where the form builder lives). Thank you.
