### ISSUE TITLE
Upgrade KoBoCat to Python3 and Django 2

### ISSUE THREAD

**Issue by noliveleger** [kobotoolbox/kobocat#602]
Step 0 - https://github.com/kobotoolbox/kobocat/pull/677
- [x] Remove edit/delete/update features from old django view.
- [x] Remove obsolete django views.
- [ ] Reviewed 

_Tests pass, current container still runs_

Step 1 - https://github.com/kobotoolbox/kobocat/pull/678
- [x] Upgrade to Python 3
- [x] Upgrade to Django 1.11
- [ ] Reviewed 

_Tests do not pass, current container does not run_

Step 2 - https://github.com/kobotoolbox/kobocat/pull/679
- [x] Bulk remove `__future__` imports
- [ ] Reviewed 

_Tests do not pass, current container does not run_

Step 3 - https://github.com/kobotoolbox/kobocat/pull/680
- [x] Bulk remove redundant `object` inheritance
- [ ] Reviewed 

_Tests do not pass, current container does not run_

Step 4 - https://github.com/kobotoolbox/kobocat/pull/682
- [x] Upgrade to Django 2.2
- [ ] Reviewed 
    
_Tests pass, current container **does not** run_

Step 5 - https://github.com/kobotoolbox/kobocat/pull/681
- [x] Use new image (same as KPI, Python 3.8&NodeJs 10)
- [x] Use non-root user to start container
- [ ] Reviewed 

_Tests pass, new container runs_

Step 6 - https://github.com/kobotoolbox/kobocat/pull/683
- [x] Refactor settings files
- [x] Use sentry new client
- [ ] Reviewed 
    
_Tests pass, new container runs_

Closes #397, closes #399

**Comment by noliveleger** [comment]
Since [commit  3c0e17d0b6041ae96b06c3ef4d2f78a2d0739cbc](https://github.com/kobotoolbox/kobocat/commit/3c0e17d0b6041ae96b06c3ef4d2f78a2d0739cbc), `pyxform.survey`'s `name` is changed to `id_string`. 
So nodes `ref` in the generated `xml` by pyxform` look like `/{id_string}/a/b.`

To be compliant with this behaviour, `uuid` in `xml` now uses this pattern too.

**Comment by Kalyan-Lama** [comment]
## Checked and ensured the following:

### Download data

- [OK] Download data (XLS)
- [OK but may have issues] Download data (CSV)
OK, but while downloading i am seeing `{}` under `_validation_status` (please see image below)
![Image 1](https://user-images.githubusercontent.com/50188479/91321307-34094480-e7de-11ea-9b36-5315b9c5d56b.png)
- [OK] Download data (ZIP)
- [OK] Download data (KML)

### Photos

- [OK] View gallery
- [OK] Download all photos 

### GPS Points

- [OK] Download GPS points

### Additional: from KC UI

- [OK] **Forms:** It takes you back to the KPI dashboard
- [OK] **Question Library:** It takes you back to the KPI Library
- [OK] **Projects:** It lists out all the projects in the KC UI
- [OK but may have issues] **Sign out:** It logs you out but you get this message (please see image below)

![Image 2](https://user-images.githubusercontent.com/50188479/91322635-b21a1b00-e7df-11ea-8534-5fb3e16fedc9.png)

### Additional: 
*(KPI UI that is linked with KC UI)*

- [OK] **deploying/redeploying projects** in the KPI UI deploys/redeploys a project in the KC UI
- [OK] **collected data synced** with the KoBoToolbox server as seen in the KPI UI is also updated (synced) in the KC UI
- [OK] **data when deleted** in the KoBoToolbox server as seen in the KPI UI is also updated (synced) in the KC UI
- [OK] **deleting project** in the KPI UI deletes a project in the KC UI
- [OK] **archiving/unarchiving projects** in the KPI UI archivs/unarchivs a project in the KC UI
- [OK] **sharing projects** in the KPI UI makes the username visible in the KC UI
