### ISSUE TITLE
Create short questionnaire for legacy features still used

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#647]
Related to https://github.com/kobotoolbox/kobocat/issues/602, we need to ask users to let us know which functionality they still require:

* Why do you still use this Legacy version of kobocat? What features are you still using? [multiple select]
* Have you tried using these features in the new interface?

We also need an introduction paragraph that can be used in the kobocat start page and on the forum.

**Comment by tinok** [comment]
Let's add a banner message to encourage users to take the survey. Here is the draft copy: 

## The legacy interface will soon disappear. Please let us know how and why you are still using it. 

We are planning to remove some or all of it’s the components from this legacy user interface for viewing project data (also known as kobocat). We introduced the new user interface in 2016 which eventually included access to all features that were previously only available in the legacy interface (and many more features). Maintaining the legacy interface functionality and security involves a lot of work and costs for our donors. Today, only a very small number of users still access the legacy user interface—including you.

We announced a while ago on this page that deploying projects on the legacy interface was highly discouraged and that its user interface will be removed “shortly”. We care deeply about our users, so before we disable the legacy interface completely, we ask you to let us know why you are still using the old user interface. This should not take more than 3 minutes.

**Take survey now**

**Comment by Ig-Rebollo** [comment]
@tinok Some options here for the banner:

Over the content:
![KoBoCAT-bannerA](https://user-images.githubusercontent.com/22472326/92257067-9cbd8480-eea2-11ea-8e30-6061b7847afb.jpg)

Pushing the content down:
![KoBoCAT-bannerB](https://user-images.githubusercontent.com/22472326/92257075-a1823880-eea2-11ea-9667-a0f21c769c6a.jpg)

**Comment by tinok** [comment]
I prefer the second option, but they are both good. My main question is whether the option to close the message will be complicated given how `kobocat-templates` works. @magicznyleszek what do you think?

We still need the small banner on top of these pages:

![image](https://user-images.githubusercontent.com/673511/92260991-beb90600-eea6-11ea-9b5e-4c47fa1952bc.png)

**Comment by Kalyan-Lama** [comment]
My opinion here would be like could we make the message cover the entire screen at the beginning. This message screen should go off only if the user chooses either a close button `[X]` or a `TAKE SURVEY NOW` button. @tinok @Ig-Rebollo

**Comment by magicznyleszek** [comment]
@tinok I've never done any serious FE work at kobocat, but closing with "x" shouldn't be a problem - I'll just include a small inline javascript script :)

**Comment by Ig-Rebollo** [comment]
I think we could repurpose option 1 to do what @Kalyan-Lama suggested. It might be a good idea to make it a pop up because by covering the content with it we are literally forcing users to look at it. With option 2 @tinok they could potentially scroll down and continue working. In any case, as you said, both would work ok, so I'd be happy with either option.

Regarding the small banner for the project pages, is there a shorter text? or would it be the same text, just more compact? If we make it s pop-up as described above, we could also use the same one for all pages. If you saw it in the previous page it won't appear, but if you access the project page directly (for instance following a link somewhere else to it) then you would see the pop up in the project page. Essentially, it shows up wherever you 'start your session'. Would this be possible @magicznyleszek ?

**Comment by Ig-Rebollo** [comment]
See here the pop up alternative @tinok @Kalyan-Lama @magicznyleszek 

![KoBoCAT-bannerC](https://user-images.githubusercontent.com/22472326/92267823-4dca1c00-eeaf-11ea-9111-c02a06103024.jpg)

**Comment by tinok** [comment]
> @tinok I've never done any serious FE work at kobocat, but closing with "x" shouldn't be a problem - I'll just include a small inline javascript script :)

@magicznyleszek Sure, closing is easy :) What I tried to say was that we would need to save this state in a cookie or other way so that they don't have to close the notification every time they open any kobocat page.

**Comment by tinok** [comment]
It took me about 70 seconds to fill in the form, so let's change the copy to "..no more than a minute".

**Comment by Ig-Rebollo** [comment]
@Tino isn't 70 seconds literally 'more than a minute'? ;)

After thinking a bit further about it, I believe the best solution might be to display the pop-up (first time you access KoBoCAT, independent of which page within KoBoCAT) and allow users to close it. Once you close the pop-up, it becomes a more compact banner on top that you can never close. 

The rationale is that some users (myself included) would be tempted to close the pop-up thinking they will do it later, once they finish whatever task they have at hand. We should then allow them to access, use KoBoCAT, and then take the survey any time they want.

This would be the most effective way to do it without being aggressive. The aggressive option would be that you can't close the pop-up window unless you click on the survey button, but that might be excessive and could alienate some.

Here the 'compact' banner:
![KoBoCAT-bannerD](https://user-images.githubusercontent.com/22472326/92269122-88cd4f00-eeb1-11ea-8eaf-0bf2fd8d2728.jpg)

**Comment by Ig-Rebollo** [comment]
Leaving here the icon in case it is needed for implementation:

[icon-02.svg.zip](https://github.com/kobotoolbox/kobocat/files/5176976/icon-02.svg.zip)

**Comment by magicznyleszek** [comment]
@tinok I will need a green light for this and a link to the survey :)

**Comment by tinok** [comment]
@magicznyleszek Please go ahead! Could you confirm if the popup can be hidden if someone has previously clicked to close it (and display the banner as @Ig-Rebollo suggested)? Sounds great from a UX perspective, but I want to make sure this doesn't balloon the time needed for this small feature.

**Comment by magicznyleszek** [comment]
@tinok does the survey from "Take survey now" exist already?

**Comment by noliveleger** [comment]
@tinok, @jnm  can we close this issue as it has been deployed to servers?

**Comment by tinok** [comment]
Yes, this is deployed on production and can be closed.
