### ISSUE TITLE
Form media not included when editing a submission

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#658]
When editing submissions, the Enketo form does not include any attachments. As a result, images/videos/audio included in the original form as labels are not displayed. This makes editing these kinds of forms difficult. For forms that use CSV files editing becomes impossible. 

## Expected behavior
Form media are included and displayed, CSV are available if used--just like in the original form:
![image](https://user-images.githubusercontent.com/673511/95603635-8c11a880-0a24-11eb-96ec-8192df818c7f.png)

## Instead

No form media are displayed / included:
![image](https://user-images.githubusercontent.com/673511/95603514-6389ae80-0a24-11eb-8c10-08aca3cd0e0d.png)

As per @MartijnR, this "is nicely documented in Enketo's API here: https://apidocs.enketo.org/v2#/post-instance (see instance_attachments and also the code sample may be useful)." This is already implemented in OpenClinica.

**Comment by MartijnR** [comment]
Note, that the feature only relates to user-uploaded files that are part of a submission, not files belonging to the form. Since you mention CSV files, I wonder if you're experiencing a different issue. Any media and data files belonging to the form description itself (so not uploaded as part of the submission by the user) should be loaded in edit mode without any additional effort.

**Comment by tinok** [comment]
@MartijnR there may be a misunderstanding then. I'm not talking about user-submitted data but form media attached to the xform. When we discussed this issue on [FD](https://www.flowdock.com/app/kobotoolbox/support/threads/50qxQwT-b5g6ZYqD1lG0sY3qkRr) this was about editing previously submitted data. The same problem occurs with CSV files used in the original form.

**Comment by tinok** [comment]
So maybe this is really a bug then?

**Comment by Kalyan-Lama** [comment]
Link to the community forum: https://community.kobotoolbox.org/t/issue-with-jpg-media-files-not-showing-in-form-when-in-edit-mode-kobotool-enketo/11898

**Comment by jamt-git** [comment]
Hi everybody,

I'm the kobotoolbox user who originally reported this issue on the kobotoolbox community forum.
I'm not very familiar with the github workflow, and I would like to kindly ask what the next steps for this issue are and whether anybody is taking action on this? Is there anything I can do to help? 
Thank you in advance for your time and interest!
JAM

**Comment by jamt-git** [comment]
As an additional comment, I did troubleshoot the bug as much as I could at the time of my original posting back in August, and I believe I identified what the problem seemed to be (it's all explained in detail in the kobotool community forum posting). I just do not have the slightest idea on what to do to solve it, so if there are any suggestions from any of the more knowledgeable members here, I'm more than willing ready to contribute my time -assuming it's within my knowledge capabilities!-
Thx again,
JAM

**Comment by tinok** [comment]
@jamt-git We're not actively working on this and it's not yet on our immediate roadmap because of a lot of other priorities. However, thanks to your report the issue is now on our radar and we'll update this issue once it's clear how and when this will be addressed in kobocat. 
cc @noliveleger

**Comment by jamt-git** [comment]
Hell Tino, and thank you for your kind message.

I understand, and this sets clear -albeit discouraging- expectations that I
can pass on to my stakeholders.

I want to take the opportunity to thank you personally for your post(s) on
the usage of the kobotoolbox API, that I have read and re-read numerous
times; they helped me integrate and automate most of the functionality we
needed four our purposes.

And again, should you have any suggestions on:
1. how I could bypass this issue
2. how I could collaborate to solve it

please don't hesitate to drop a message.

Thanks again for your time and your work for the community,

JAM

**Comment by tinok** [comment]
Thanks for taking the time to document this. Based on your images on the forum post it seems like it's a smaller issue than I expected. @noliveleger the problem seems that the TLD is set to `internal` instead of `org`.

![image](https://user-images.githubusercontent.com/673511/96631147-f27bae00-12e3-11eb-997e-7b3e4449d2a8.png)

**Comment by noliveleger** [comment]
@tinok, I'm not sure it's the problem. EE is serving as a proxy for images hosted at KC. So, on the server side, EE is able to read images from `http://kc.kobotoolbox.internal` (which is a valid internal docker network url). 
I have to double check to be sure that's not the browser which accesses it directly.

**Comment by noliveleger** [comment]
Finally, it is related to SSRF protection which blocks private domain name resolving. 

What's happening:
- KPI asks for Enketo Express edit link, it uses KC as a proxy on the private domain name. (e.g. `kc.domainname.internal`). 
- KC `POST`s to EE API to get edit link. Among the parameters, KC sends the current domain name
- EE prepares the form in edit mode and create absolute links to media with the domain it just received. 


**KC sends a request to EE**:
https://github.com/kobotoolbox/kobocat/blob/46108fd02f08f15ed6a841510dd83472e2fee010/onadata/libs/utils/viewer_tools.py#L266

**KC retrieve its domain name**:
https://github.com/kobotoolbox/kobocat/blob/46108fd02f08f15ed6a841510dd83472e2fee010/onadata/libs/utils/viewer_tools.py#L242-L258

I guess we should force KC public domain name all the time. So `_get_form_url()` should be rewritten to only use `settings.KOBOCAT_URL`
