### ISSUE TITLE
deletedat always null

### ISSUE THREAD

**Issue by kryptt** [kobotoolbox/kobocat#659]
deletedat is never reflected in the postgres tables. 

reproduction: delete a submission instance
effects: 
instance is no longer visible or found in mongo
but the deletedat field is never set in postgres.

**Comment by jnm** [comment]
Hello, are you saying that the submission's row remains in Postgres' `logger_instance`? Thanks

**Comment by jnm** [comment]
Additional info from https://github.com/kobotoolbox/kobocat/pull/552#issuecomment-512659513
> tbh, KoBoToolbox has abandoned `deleted_at` altogether after we discovered that it's set only by the [legacy view](https://github.com/kobotoolbox/kobocat/blob/82111fabc5824bf06ad73c7666919972d03f479d/onadata/apps/main/views.py#L1247), which we intend to remove, and not by the [data API](https://github.com/kobotoolbox/kobocat/blob/82111fabc5824bf06ad73c7666919972d03f479d/onadata/apps/api/viewsets/data_viewset.py#L581-L598). It also seems more consistent with people's expectations (and perhaps regulations) to really erase data when instructed to do so. Plus, there was never any way for someone to undelete their deleted submissions—only a sysadmin could recover them.

**Comment by kryptt** [comment]
> Hello, are you saying that the submission's row remains in Postgres' `logger_instance` after deleting? That would be surprising, and a bug. Thanks

Hmm, thanks for the update! 

I do not have them in logger_instance, but they are still in logger_instancehistory and the reversion_version tables...

**Comment by jnm** [comment]
I have to admit, I haven't dug into [`InstanceHistory`](https://github.com/kobotoolbox/kobocat/blob/cb3f17873c49759fcc52f0d7b69f0c73e13ef289/onadata/apps/logger/models/instance.py#L425-L436) / `logger_instancehistory`. The [django-reversion](https://github.com/etianen/django-reversion/) stuff is expected, but I wouldn't rely on it (it sounds like you're not) because we may trash it.

If you'd rather eliminate reversion now, you can stop the `Instance` model from being registered with it:
https://github.com/kobotoolbox/kobocat/blob/828081dde9ac211e0ef512f7db3410abf3dcb0f2/onadata/apps/logger/models/instance.py#L117-L118

**Comment by jnm** [comment]
I don't know if you have any time to look into this, but could you tell if `logger_instancehistory` rows are only added when a submission is edited? In other words, I'd be curious to know if `logger_instancehistory` doesn't receive anything when a submission is created or deleted, but only when it's edited. Then, based on what you said earlier, it sounds like whatever `logger_instancehistory` rows may have been created are never cleaned up when a submission is deleted.

**Comment by kryptt** [comment]
@jnm we are actually actively using the django-reversion information as it is a quick connection with the different changes for each instance. and our instances progress through time. 

In fact with the information currently in logger_instance and logger_instancehistory we would not be able to implement the custom queries we are currently performing....  It is a bit of a different use case, since we see submissions with multiple updates, but it is rather important for us to track changes for the individual submissions.

**Comment by jnm** [comment]
That's good to know. Thanks.

**Comment by jnm** [comment]
Hi @kryptt, we are preparing to remove `deleted_at` (Postgres) and `_deleted_at` (Mongo) for performance reasons. We will stop setting these attributes in the [legacy view](https://github.com/kobotoolbox/kobocat/blob/d91834ccb174da0fd0305f8e8ae11ed93cce10c0/onadata/apps/main/views.py#L1196) and delete the submissions outright, as was always done for `DELETE` HTTP requests to the API. We will also include a migration that deletes all rows in Postgres' `logger_instance` that have any non-null value for `deleted_at`, and likewise remove any documents in the Mongo `instances` collection that have `_deleted_at` set.

django-reversion and `logger_instancehistory` will not be changed. If I've read your previous comments correctly, your workflow should not be affected, but I wanted to notify you just in case.

**Comment by kryptt** [comment]
@jnm Thanks for the heads up! I believe we will indeed not be heavily affected by this change!
