### ISSUE TITLE
normalize-space() not working in calculate fields

### ISSUE THREAD

**Issue by galalH** [kobotoolbox/kobocat#662]
The title says it all. I’ve tried deploying xlsforms that use normalize-space() in both kobo.humanitarianresponse.info & kobo.unhcr.org but neither one would let me.

Here’s a minimalist example of an xlsform that triggers the error:

```
type	        name	     label	        calculation
calculate	test		                normalize-space('foo    bar')
```
And here’s the text of the error message that comes up:

> your form cannot be deployed because it contains errors:
> 
> ODK Validate Errors: >> Something broke the parser. See above for a hint. Error evaluating field ‘test’: The problem was located in calculate expression for ${test} XPath evaluation: cannot handle function ‘normalize-space’ Caused by: org.javarosa.xpath.XPathUnhandledException: The problem was located in calculate expression for ${test} XPath evaluation: cannot handle function ‘normalize-space’ … 10 more Result: Invalid

Any support with the issue would be greatly appreciated.

Cross-posted to the [KoBoToolbox Community Support Forums](https://community.kobotoolbox.org/t/cant-deploy-forms-using-normalize-space/13517). @wroos there mentioned that it's working fine on ODK.

**Comment by jnm** [comment]
This should be handled by #604

**Comment by jnm** [comment]
Please see kobotoolbox/kpi#2864
