### ISSUE TITLE
Allow for view-only previews of submissions

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kobocat#671]
As outlined [here](https://community.kobotoolbox.org/t/ability-to-view-completed-submissions-in-enketo-and-ideally-pdf-them/15457) by [nat](https://community.kobotoolbox.org/u/nat) in the community, we need to allow for users to access a view-only preview of submissions. This feature is already implemented by Enketo and just needs to be integrated into kobocat/kpi to expose it.

**Comment by nanometrenat** [comment]
xref https://github.com/kobotoolbox/kpi/issues/3312
