### ISSUE TITLE
 [Python3 and Django2.2 upgrade] Punch list

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobocat#691]
- [x] !!high priority!! test permission thing
    https://github.com/kobotoolbox/kobocat/pull/682#discussion_r592843313
- [x] comment should be removed
    https://github.com/kobotoolbox/kobocat/pull/678#discussion_r591912260
- [x] pointless ModelSerializer initialization
    https://github.com/kobotoolbox/kobocat/pull/678#discussion_r592728758
- [x] remove prefetch_related
    https://github.com/kobotoolbox/kobocat/pull/678#discussion_r591994888
- [x] trash old redirect middleware
    https://github.com/kobotoolbox/kobocat/pull/682#discussion_r592846268
- [ ] remove CountryField if unused
    https://github.com/kobotoolbox/kobocat/pull/682#discussion_r592847102
- [x] add remark to pyxform upgrade
    https://github.com/kobotoolbox/kobocat/pull/682#discussion_r592848507
- [x] test odk collect bad http header
    https://github.com/kobotoolbox/kobocat/pull/682#discussion_r592848198
    it's been fixed! https://github.com/getodk/collect/pull/3269

**Comment by JacquelineMorrissette** [comment]
For the Test Permission Thing - It doesn't appear that the permission object is removed from the database for existing projects. The `view_xform` permission still exists with the same primary key it has in master

**Comment by noliveleger** [comment]
> add remark to pyxform upgrade

I've removed the monkey patch since `pyxform` has been upgraded and merged into `beta`
