### ISSUE TITLE
Kobocat 2.0 notification

### ISSUE THREAD

**Issue by magicznyleszek** [kobotoolbox/kobocat#700]
We need a simple banner/message to let people know that we are soon disabling a number of features in kobocat (aka Legacy Interface). This could be modeled after the survey banner we have now (replacing it).

Here is the link to the Figma files to get all the specs: https://www.figma.com/file/GLervyxkFfCQbn22ydkmVd/Legacy-notification?node-id=0%3A1

Please use the updated text from the forum post: https://community.kobotoolbox.org/t/changes-to-legacy-interface-self-serve-migration-feature-into-the-new-interface/18108

**Comment by jnm** [comment]
Please do this work on top of `master`
