### ISSUE TITLE
API docs typo

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kobocat#701]
The docs at `/api/v1/data` have an example with the following:
```
curl -X GET 'https://example.com/api/v1/data/22845?query={"date": {"gt$": "2014-09-29T01:02:03+0000"}}'
```
But should be:
```
curl -X GET 'https://example.com/api/v1/data/22845?query={"date": {"$gt": "2014-09-29T01:02:03+0000"}}'
```
(`gt$` 👉 `$gt`)

Based on https://community.kobotoolbox.org/t/send-data-transparently-to-our-server/17629/9

**Comment by jnm** [comment]
Fixed by #702
