### ISSUE TITLE
Portrait photos submitted through Collect or Enketo confuse their orientation

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kobocat#707]
Originally noted in the community here: https://community.kobotoolbox.org/t/portrait-photos-imported-through-kobocollect-are-sideways-bug-report/17435/3

## Method to reproduce (from original post)

1. Create a simple form containing a photo uploader
1. Using KoBoCollect, take a photo on a device that produces an EXIF Orientation tag for portrait photos and upload it via the form
1. Download the photo from KoBoToolbox and render on any system that understands EXIF Orientation. (This includes the standard thumbnail and picture viewers in Windows 10 File Explorer.)
1. Notice that landscape photos render correctly, but portrait photos are sideways
1. Contrast with same photo source, with the photo file copied directly to the renderer (Windows 10 File Explorer, for example), where portrait photos are displayed vertical as expected

**Comment by Kalyan-Lama** [comment]
For community reference: https://community.kobotoolbox.org/t/portrait-photos-imported-through-kobocollect-are-sideways-bug-report/17435

**Comment by jnm** [comment]
Internal discussion: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/Parking.20Lot.20.3A.20Time.20Intensive.20Support.20Tickets/near/24091

**Comment by jnm** [comment]
These things should be byte-for-byte duplicates for a given photo attachment:

1. The output of https://kc.kobotoolbox.org/media/original
2. The photo as included in the ZIP export
3. The photo as saved by ODK Collect in (on my device, that's in `Internal/Android/data/org.odk.collect.android/files/instances/<instance directory>/`)

…and indeed they are, when tested with my Pixel XL running Android 10 and ODK Collect v1.30.1:
```
$ md5sum *
1eb457acac9ab31c9d1cafa12eede99d  1-internal-android.jpg
1eb457acac9ab31c9d1cafa12eede99d  1-kc-media-original.jpg
1eb457acac9ab31c9d1cafa12eede99d  1-zip-export.jpg
f80df0bb0bf9d2ac8079899d8767cb32  2-internal-android.jpg
f80df0bb0bf9d2ac8079899d8767cb32  2-kc-media-original.jpg
f80df0bb0bf9d2ac8079899d8767cb32  2-zip-export.jpg
356711369bf2e481e724b4d99641831a  3-internal-android.jpg
356711369bf2e481e724b4d99641831a  3-kc-original.jpg
356711369bf2e481e724b4d99641831a  3-zip-export.jpg
```

@joshuaberetta, @Kalyan-Lama, @StephaneAloo this is certainly low priority, but when time permits more work on it, let's please:

1. Get the person reporting the issue to retrieve the image directly from their Android device—see my point (3) above. With that, they can answer their own question:
    > The solution is an either/or one, somewhere inside either KoBoCollect or the import side of KoBoToolbox (I cannot identify which is at fault here)
    * If the file retrieved directly from the Android device still has the incorrect EXIF information (hint: it will), then ask them to try with the latest version of ODK Collect. If the behavior remains the same, then the problem needs to be reported on forum.getodk.org or at https://github.com/getodk/collect/issues/, with **exact** reproduction steps. I do not envy the Collect developers here: rotation handling looks like a [mess](https://github.com/getodk/collect/issues/36#issuecomment-336377454) of unpredictable, device-specific behavior.
2. If there is an issue with KoBoToolbox, the web application, then we really do need exact reproduction steps—for this and *all* bug reports. Those aren't included in the description of this issue and they weren't included in the original report in the forum. In other words, in response to the post below, the answer we should give is "Please do reply with specifics! We do need a list of unambiguous reproduction steps to properly diagnose this issue."
    > It’s primarily through the V1 API but I *think* it’s also via the Forms Management interface (alongside downloading data as a spreadsheet, etc.)
    > If that’s sufficient, great. Otherwise I’ll pick this up on Monday/Tuesday, when I’m back in the office, with specifics
    
    Until we get an answer, don't spend your very limited time guessing at what they might've been trying to do. There are exceptions, of course: if an issue looks like a critical problem (e.g. potential data loss), then please do pursue it aggressively even if the user's report is incomplete.

Thank you :pray:

**Comment by roaima** [comment]
As the person who originally submitted the issue on the Community Forum, please allow me to respond to your points

1. The issue isn't with photos taken on my device and copied directly to Windows. The issue occurs only when going through KoBoCollect app and extracted from the KoBoToolbox server application. I cannot identify whether it is KC or KT that is at fault, as the process I'm using involves both components and I don't have the means to separate them.
2. I provided reproduction steps in my community post. The subsequent statement that you've quoted says "_If that's sufficient, great, otherwise..._". I had no feedback on that offer until your post just now, so I'll get on to it for you.

Thanks

**Comment by jnm** [comment]
>     1. The issue isn't with photos taken on my device and copied directly to Windows. The issue occurs only when going through KoBoCollect app and extracted from the KoBoToolbox server application. I cannot identify whether it is KC or KT that is at fault, as the process I'm using involves both components and I don't have the means to separate them.

@roaima, did you take the picture with KoBoCollect and copy from the directory that I specified? I found different behavior when taking the picture with Collect vs. using the built-in Android camera application. This highlights why we need unambiguous reproduction steps. Yes, what you provided was not sufficient. I do apologize for our delay in asking you for more details. Thanks for following up with more information.

**Comment by roaima** [comment]
This has been an interesting investigation. I have been using two photos, one landscape with no EXIF Orientation tag and one portrait with an Orientation tag value "Rotate 90 CW" (this is an instruction to the renderer, i.e. turn the image clockwise by 90° when you want to process it or display it to the user).

My own phone doesn't use EXIF Orientation tags for differentiating portrait and landscape photos. Instead it just writes the image to match the orientation of the phone, i.e. X and Y swap depending on the orientation. Consequently I haven't yet been able to test with taking an actual photo, just choosing constructed ones. (My field staff don't necessarily speak English so it takes time to ask them to perform specific tests for me.)

Creation process
1. Create two photos: one landscape with X=1000 Y=750, one portrait also with X=1000 Y=750 but with an EXIF Orientation tag = "Rotate 90° CW".
2. Create and deploy form to accept two photos and a comment/description
3. Use form in KoBoCollect 1.30.1 and Enketo webforms to upload the pair of images

Extraction process
- I extracted the pair of photos from my phone's filesystem (KoboCollect), from the KoBo server filesystem (KoBoToolbox), and as a download from the forms management interface.

My results
- KoboToolbox gallery shows thumbnails visually,
  - Phone:      Visually correct (i.e. portrait phone has either Orientation or rotation applied)
  - Enketo:     Landscape correct, portrait facing left (i.e. neither rotation nor orientation applied)

- Downloaded ZIP of media shows pictures visually,
  - Phone:      image 1: ok, image 2: ok
  - Enketo:     image 1: ok, image 2: rotated 90' clockwise (image corrected BUT Orientation tag still applied)

- MD5 checksums show the following relationships
  - Portrait photo
    - KoboToolbox filesystem = Downloaded (Enketo submission) from KoboToolbox = Original
    - KoboCollect filesystem = Downloaded (Phone submission) from KoboToolbox = BUT IS NOT ORIGINAL
  - Landscape photo
    - KoboCollect filesystem = Downloaded (Phone submission) from KoboToolbox = BUT IS NOT ORIGINAL
    - KoboToolbox filesystem = Downloaded (Enketo submission) from KoboToolbox = Original

My analysis
- The photo image is rotated according to the Orientation tag in the KoBoCollect app at the point the image is Chosen while entering data into a form. Either this rotation should not occur or the Orientation tag should be removed from the resulting image
- The photo image is not changed in any way when submitted through Enketo (this is correct behaviour)
- I do not have enough data to identify if there is a difference between taking a photo on the phone device and choosing an existing file

Supporting files
- [Portrait vase](https://user-images.githubusercontent.com/3172148/119019351-06c87c00-b995-11eb-9010-97c990b9e943.jpg)
- [Landscape vase](https://user-images.githubusercontent.com/3172148/119019354-07611280-b995-11eb-9152-734e86e6a85d.jpg)
- [Test photo orientation (2).xlsx](https://github.com/kobotoolbox/kobocat/files/6517614/Test.photo.orientation.2.xlsx) (XLSForm)

**Comment by jnm** [comment]
I believe this will be corrected by https://github.com/getodk/collect/issues/4571. If there's another aspect of the problem that needs separate attention, please re-open this issue and describe what additional fixes are necessary.
