### ISSUE TITLE
ODK Briefcase compatibility issues

### ISSUE THREAD

**Issue by joshuaberetta** [kobotoolbox/kobocat#772]
- Zulip disucssion: https://chat.kobotoolbox.org/#narrow/stream/6-Support/topic/ODK.20Briefcase/near/66403
- Reports:
  - https://community.kobotoolbox.org/t/unable-to-download-data-from-kobotoolbox-server-using-odk-briefcase/6326/27
  - https://community.kobotoolbox.org/t/internal-server-error-when-downloading-encrypted-forms/4212/18
  - https://github.com/getodk/briefcase/issues/859

Affects encrypted forms and forms with attachments since ODK Briefcase downloads submissions as attachments. 
The issue is that the new ODK Briefcase (> `1.15`) does not send the correct headers when fetching attachments: 

- ODK Briefcase 1.15:
```python 
{
  'Host': 'kc.kobo.local:8001',
  'X-Real-Ip': '172.16.52.1',
  'X-Forwarded-For': '172.16.52.1',
  'X-Forwarded-Proto': 'http',
  'X-Forwarded-Host': 'kc.kobo.local',
  'Connection': 'close',
  'X-Openrosa-Version': '1.0',
  'Date': 'Tue, 19-Oct-21 21:10:40 GMT',
  'User-Agent': 'Apache-HttpClient/4.5.5 (Java/1.8.0_301)',
  'Accept-Encoding': 'gzip,deflate',
  'Authorization': 'Digest username="oleger_user",  ....'
}
```

- ODK Briefcase 1.18:
```python 
{
  'Host': 'kc.kobo.local:8001', 
  'X-Real-Ip': '172.16.52.1',
  'X-Forwarded-For': '172.16.52.1',
  'X-Forwarded-Proto': 'http',
  'X-Forwarded-Host': 'kc.kobo.local',
  'Connection': 'close',
  'X-Openrosa-Version': '1.0',
  'User-Agent': 'Apache-HttpClient/4.5.5 (Java/1.8.0_301)',
  'Accept-Encoding': 'gzip,deflate'
}
```

Therefore the user is never authenticated.

**Comment by jnm** [comment]
It's a bit counterintuitive, but I think ODK Briefcase is following the specification to the letter by sending the unauthenticated request first: https://docs.getodk.org/openrosa-authentication/#digest-authentication-example-interaction

You can also see this behavior when Enketo requests forms (and likely the same thing for ODK Collect as well). I hope @noliveleger doesn't mind me pasting his old research from Flowdock here :smile:

> Oli [on May 13, 2020](https://www.flowdock.com/app/kobotoolbox/kobo/messages/1278419)
> 
> I've looked at the submission process in ee.
> When a form is opened in ee, it `GET`s
> 
> -   /`<username>`/formList?formID=`<form_idstring>`
> -   /`<username>`/xformsManifest/`<id>`
> 
> When `Require authentication to see forms and submit data` is checked, both urls are called twice.
> Once with no digest headers, once with digest headers.
> 
> For example on my local dev, I get:
> 
> ```
> 172.29.0.5 - - [13/May/2020 15:14:36] "GET /oleger_user/formList?formID=arMtEixLHJuhuUFaxKL4ug HTTP/1.0" 401 -
> 172.29.0.5 - - [13/May/2020 15:14:36] "GET /oleger_user/formList?formID=arMtEixLHJuhuUFaxKL4ug HTTP/1.0" 200 -
> 172.29.0.5 - - [13/May/2020 15:14:36] "GET /oleger_user/xformsManifest/1 HTTP/1.0" 401 -
> 172.29.0.5 - - [13/May/2020 15:14:37] "GET /oleger_user/xformsManifest/1 HTTP/1.0" 200 -
> 
> ```
> 
> Both `401` requests don't have any headers related to Digest. Subsequent successful requests do hit the DB (`django_digest_usernonce` table) .
> 
> From my PostgreSQL logs:
> 
> ```
> 61813 [2020-05-13 15:17:39 UTC] LOG:  statement:
> 61814         UPDATE django_digest_usernonce SET count = 1, last_used_at = '2020-05-13T15:17:39.647467'::timestamp
> 61815           WHERE django_digest_usernonce.nonce = '1589383059.58:415C:13a4e1316a2acf23d426543d57b668cf'
> 61816             AND django_digest_usernonce.user_id = 2
> 61817             AND django_digest_usernonce.count < 1
> 61818
> 61819 [2020-05-13 15:17:39 UTC] LOG:  statement:
> 61820         SELECT django_digest_usernonce.last_used_at FROM django_digest_usernonce
> 61821           WHERE django_digest_usernonce.user_id = 2
> 61822           ORDER BY django_digest_usernonce.last_used_at DESC LIMIT 1 OFFSET 31
> 61823
> 61824 [2020-05-13 15:17:39 UTC] LOG:  statement:
> 61825         INSERT INTO django_digest_usernonce (user_id, nonce, count, last_used_at)
> 61826           VALUES (2, '1589383059.58:415C:13a4e1316a2acf23d426543d57b668cf', 1, '2020-05-13T15:17:39.658289'::timestamp)
> 
> 61851 [2020-05-13 15:17:39 UTC] LOG:  statement:
> 61852         UPDATE django_digest_usernonce SET count = 1, last_used_at = '2020-05-13T15:17:39.819548'::timestamp
> 61853           WHERE django_digest_usernonce.nonce = '1589383059.75:41F9:e03a966893c655d1d6033e65ee7e5051'
> 61854             AND django_digest_usernonce.user_id = 2
> 61855             AND django_digest_usernonce.count < 1
> 61856
> 61857 [2020-05-13 15:17:39 UTC] LOG:  statement:
> 61858         SELECT django_digest_usernonce.last_used_at FROM django_digest_usernonce
> 61859           WHERE django_digest_usernonce.user_id = 2
> 61860           ORDER BY django_digest_usernonce.last_used_at DESC LIMIT 1 OFFSET 31
> 61861
> 61862 [2020-05-13 15:17:39 UTC] LOG:  statement:
> 61863         INSERT INTO django_digest_usernonce (user_id, nonce, count, last_used_at)
> 61864           VALUES (2, '1589383059.75:41F9:e03a966893c655d1d6033e65ee7e5051', 1, '2020-05-13T15:17:39.824456'::timestamp)
> 
> ```
