### ISSUE TITLE
Fix race condition issues with Kobocat

### ISSUE THREAD

**Issue by JacquelineMorrissette** [kobotoolbox/kobocat#800]
There is a race condition which may lead to duplicate entries in the submission counter by adding a composite key and making changes to the signal to user `get_or_create()`.
Excess entries for the month need to be removed in the migration as well

**Comment by jnm** [comment]
I like this as a reference for `get_or_create()` and have found it helpful more than a few times: https://adriennedomingus.com/blog/the-perils-of-getorcreate-race-conditions
