### ISSUE TITLE
Ensure xml_hash is not null and stop doing full-text search

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobocat#843]
- [ ] add data migration
- [ ] enforce uniqueness on `xml_hash`?
- [ ] get rid of this full-text search:
https://github.com/kobotoolbox/kobocat/blob/c7e9cf092bdaa355170ee91f45ba7d19882662e1/onadata/libs/utils/logger_tools.py#L165-L168

**Comment by noliveleger** [comment]
Closed because it is handled by kobotoolbox/kpi#5047
