### ISSUE TITLE
Add option under exports to exclude group names

### ISSUE THREAD

**Issue by tinok** [kobotoolbox/kobocat#85]
" As a user I want to only see a table with the variable names as headers, regardless of which group they were in. Most of my groups only exist for aesthetic purposes (field-list) and have no relation with the data itself. "

This might have been addressed by the Google/Nepal PR already, which includes this option in the code.

**Comment by esmail** [comment]
"Include groups in headers" checkbox now available under "Advanced Downloads (beta)", but seems to have no effect.

See: https://support.kobotoolbox.org/customer/portal/questions/16680333-data-download-problem

**Comment by jnm** [comment]
Closing since this is fixed in KC (but not in KPI, see https://github.com/kobotoolbox/kpi/issues/1016)
