### ISSUE TITLE
Max zoom level on form makes distinguishing points difficult

### ISSUE THREAD

**Issue by DerekCaelin** [kobotoolbox/kobocat#854]
![image](https://user-images.githubusercontent.com/10799815/202021773-0eea7cee-b488-487e-9aba-e2cec8f38cad.png)

Our partners use KoBo to collect polygon data, sometimes smaller than a half-hectare. It would be helpful to be able to zoom in when reviewing the data to distinguish the points better (or, if the points were reduced in scale).

**Comment by jnm** [comment]
Moved to https://github.com/enketo/enketo-express/issues/514 since this will require a change to Enketo.
